import assert from "node:assert/strict";
import {
  mkdtempSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  VERSION_PATTERN,
  setVersionFromTag,
} from "./set-version-from-tag.mjs";

function fixtureDesktop(root) {
  mkdirSync(join(root, "src-tauri"), { recursive: true });
  writeFileSync(
    join(root, "package.json"),
    `${JSON.stringify({ name: "buzz", version: "0.5.18" }, null, 2)}\n`,
  );
  writeFileSync(
    join(root, "src-tauri/tauri.conf.json"),
    `${JSON.stringify(
      {
        productName: "Hula Buzz",
        version: "0.5.18",
        identifier: "com.huladesk.buzz",
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(
    join(root, "src-tauri/Cargo.toml"),
    `[workspace]
members = ["crates/buzz-terminal"]

[package]
name = "buzz-desktop"
version = "0.5.18"
description = "Buzz desktop app"
edition = "2021"

[dependencies]
anyhow = "1"
`,
  );
  writeFileSync(
    join(root, "src-tauri/Cargo.lock"),
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "buzz-desktop"
version = "0.5.18"
dependencies = [
 "anyhow",
]
`,
  );
}

test("VERSION_PATTERN accepts Hula Block-base + sub-increment tags", () => {
  assert.equal(VERSION_PATTERN.test("0.5.23"), true);
  assert.equal(VERSION_PATTERN.test("0.5.23-hula.2"), true);
  assert.equal(VERSION_PATTERN.test("0.5.23-beta.1"), true);
  assert.equal(VERSION_PATTERN.test("0.5"), false);
  assert.equal(VERSION_PATTERN.test("v0.5.23-hula.2"), false);
});

test("setVersionFromTag writes the same Hula version to every SoT file", () => {
  const root = mkdtempSync(join(tmpdir(), "hula-set-version-"));
  try {
    fixtureDesktop(root);
    const result = setVersionFromTag("0.5.23-hula.2", { cwd: root });
    assert.equal(result.version, "0.5.23-hula.2");
    assert.deepEqual(result.files, [
      "package.json",
      "src-tauri/tauri.conf.json",
      "src-tauri/Cargo.toml",
      "src-tauri/Cargo.lock",
    ]);

    assert.equal(
      JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version,
      "0.5.23-hula.2",
    );
    assert.equal(
      JSON.parse(readFileSync(join(root, "src-tauri/tauri.conf.json"), "utf8"))
        .version,
      "0.5.23-hula.2",
    );
    assert.match(
      readFileSync(join(root, "src-tauri/Cargo.toml"), "utf8"),
      /^version = "0\.5\.23-hula\.2"$/m,
    );
    assert.match(
      readFileSync(join(root, "src-tauri/Cargo.lock"), "utf8"),
      /name = "buzz-desktop"\nversion = "0\.5\.23-hula\.2"/,
    );
    // Dependency versions in the lockfile must not be rewritten.
    assert.match(
      readFileSync(join(root, "src-tauri/Cargo.lock"), "utf8"),
      /name = "anyhow"\nversion = "1\.0\.0"/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("setVersionFromTag rejects invalid versions", () => {
  const root = mkdtempSync(join(tmpdir(), "hula-set-version-bad-"));
  try {
    fixtureDesktop(root);
    assert.throws(() => setVersionFromTag("not-a-version", { cwd: root }), {
      message: /Invalid version/,
    });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
